# Tomcat
server.port: 8017

# Spring settings
spring:
    profiles.active: dev

#Elastic Search
elasticsearch:
    host:
        - 192.168.1.101
        - 192.168.1.102
        - 192.168.1.103
    port: 9200
    clusterName: elasticsearch
    clientTransportSniff: true
    minSoc : 10
    maxSoc : 97
    linearSoc : 3
    linearMileage : 3
    startDate : -3
    endDate : -1
    monthDay : -30
