# Tomcat
server.port: 8017

# Spring settings
spring:
    profiles.active: dev

#Elastic Search
elasticsearch:
    hostOne : 192.168.1.101
    hostTwo : 192.168.1.102
    hostThree : 192.168.1.103
    port : 9200
    clusterName : elasticsearch
    clientTransportSniff: true
